/// Central C import for the entire monobash project.
/// All files should import `c` from here instead of having their own @cImport.
pub const c = @cImport({
    @cDefine("_GNU_SOURCE", "1");
    @cInclude("unistd.h");
    @cInclude("sys/stat.h");
    @cInclude("sys/utsname.h");
    @cInclude("sys/wait.h");
    @cInclude("sys/resource.h");
    @cInclude("sys/statvfs.h");
    @cInclude("sys/personality.h");
    @cInclude("sys/file.h");
    @cInclude("fcntl.h");
    @cInclude("pwd.h");
    @cInclude("grp.h");
    @cInclude("stdlib.h");
    @cInclude("stdio.h");
    @cInclude("signal.h");
    @cInclude("sched.h");
    @cInclude("dirent.h");
    @cInclude("time.h");
    @cInclude("termios.h");
    @cInclude("regex.h");
    @cInclude("wordexp.h");
    @cInclude("sys/socket.h");
    @cInclude("netinet/in.h");
    @cInclude("arpa/inet.h");
    @cInclude("netdb.h");
    @cInclude("sys/socket.h");
    @cInclude("netinet/in.h");
    @cInclude("arpa/inet.h");
    @cInclude("netdb.h");
    @cInclude("net/if.h");
    @cInclude("sys/ioctl.h");
    @cInclude("poll.h");
    @cInclude("sys/time.h");
    @cInclude("netpacket/packet.h");
    @cInclude("net/if_arp.h");
    @cInclude("netinet/ip.h");
    @cInclude("netinet/ip_icmp.h");
});
