apiVersion: batch/v1
kind: Job
metadata:
  name: monobash-test-{CATEGORY}
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      containers:
      - name: tester
        image: docker.io/ubuntu:24.04
        command: ["/bin/bash"]
        args: ["-c", "export SHELL=/mnt/monobash/zig-out/bin/monobash && /mnt/monobash/zig-out/bin/monobash -c 'true' 2>&1 && bash /mnt/tests/compare.sh {CATEGORY} 2>&1; echo '---DONE---'"]
        volumeMounts:
        - name: monobash-data
          mountPath: /mnt/monobash
        - name: test-data
          mountPath: /mnt/tests
      restartPolicy: Never
      volumes:
      - name: monobash-data
        hostPath:
          path: {MONOBASH_DIR}
          type: Directory
      - name: test-data
        hostPath:
          path: {TESTS_PATH}
          type: Directory
  backoffLimit: 1
