apiVersion: v1
kind: Pod
metadata:
  name: monobash-tester
spec:
  containers:
  - name: tester
    image: docker.io/ubuntu:24.04
    command: ["/bin/bash", "-c", "sleep infinity"]
    volumeMounts:
    - name: monobash-data
      mountPath: /mnt/monobash
    - name: test-data
      mountPath: /mnt/tests
  volumes:
  - name: monobash-data
    hostPath:
      path: {MONOBASH_DIR}
      type: Directory
  - name: test-data
    hostPath:
      path: {TESTS_PATH}
      type: Directory
